export const lexicalTheme = {
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'text-gray-400 text-sm',
  paragraph: 'mb-1',
  quote: 'border-l-4 border-gray-300 pl-4 italic text-gray-600 my-2',
  heading: {
    h1: 'text-2xl font-bold mb-2 mt-4',
    h2: 'text-xl font-bold mb-2 mt-3',
    h3: 'text-lg font-bold mb-2 mt-3',
    h4: 'text-base font-bold mb-2 mt-2',
    h5: 'text-sm font-bold mb-2 mt-2',
    h6: 'text-xs font-bold mb-2 mt-2',
  },
  list: {
    nested: {
      listitem: 'list-none',
    },
    ol: 'list-decimal list-inside my-2',
    ul: 'list-disc list-inside my-2',
    listitem: 'mb-1',
  },
  link: 'text-blue-600 hover:text-blue-800 underline cursor-pointer',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    code: 'bg-gray-100 px-1 py-0.5 rounded text-sm font-mono',
  },
  code: 'bg-gray-100 p-4 rounded-lg font-mono text-sm my-2 block overflow-x-auto',
  codeHighlight: {
    atrule: 'text-purple-600',
    attr: 'text-blue-600',
    boolean: 'text-red-600',
    builtin: 'text-purple-600',
    cdata: 'text-gray-600',
    char: 'text-green-600',
    class: 'text-blue-600',
    comment: 'text-gray-500 italic',
    constant: 'text-red-600',
    deleted: 'text-red-600',
    doctype: 'text-gray-600',
    entity: 'text-orange-600',
    function: 'text-blue-600',
    important: 'text-red-600',
    inserted: 'text-green-600',
    keyword: 'text-purple-600',
    namespace: 'text-blue-600',
    number: 'text-red-600',
    operator: 'text-gray-700',
    prolog: 'text-gray-600',
    property: 'text-blue-600',
    punctuation: 'text-gray-700',
    regex: 'text-green-600',
    selector: 'text-purple-600',
    string: 'text-green-600',
    symbol: 'text-red-600',
    tag: 'text-purple-600',
    url: 'text-blue-600',
    variable: 'text-orange-600',
  },
};
